service: ece465-final-bloodbank

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  environment:
    USER_TABLE: ${self:service}-userTable
    BLOOD_TABLE: ${self:service}-bloodTable
    APPOINTMENT_TABLE: ${self:service}-appointmentTable
    APP_SECRET: qZVUS7jsA33pnM6Vi8KG
    APP_BASE_URL: "http://localhost:3000"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USER_TABLE}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.BLOOD_TABLE}"
            - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.APPOINTMENT_TABLE}"
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

functions:
  signup:
    handler: user/signup.signup
    events:
      - http:
          path: user
          method: post
          cors: true
  login:
    handler: user/login.login
    events:
      - http:
          path: user/{email}/{password}
          method: get
          cors: true
          request:
            parameters:
              paths:
                email: true
                password: true

  create:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true
          request:
            parameters:
              querystrings:
                type: true


  list:
    handler: todos/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                type: true
                name: false
                job: false
                place: false


  get:
    handler: todos/get.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: todos/update.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
          request:
            parameters:
              querystrings:
                type: true

  delete:
    handler: todos/delete.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true
          request:
            parameters:
              querystrings:
                type: true

resources:
  Resources:
    usersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_TABLE}
    bloodTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.BLOOD_TABLE}
    appointmentTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.APPOINTMENT_TABLE}
    
